__version__ = '0.1.0'
__tool_name__ = 'MongoDB Backup'
__description__ = 'Tool/class for backup and restore of MongoDB Databases'
__author__ = 'Guionardo Furlan'
__author_email__ = 'guionardo@gmail.com'
